org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true

GROUP=dev.goncaloramalho
VERSION_NAME=1.0.0
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/Turista838/flow-observer
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/Turista838/flow-observer
POM_SCM_CONNECTION=scm:git:git://github.com/Turista838/flow-observer.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Turista838/flow-observer.git
POM_DEVELOPER_ID=Turista838
POM_DEVELOPER_NAME=Gonçalo Ramalho
POM_DEVELOPER_URL=https://github.com/Turista838
POM_DEVELOPER_EMAIL=gon.es.ramalho@gmail.com